# <p align="center" style="color:#AEB6BF;">PROYECTO MACHINE LEARNING</p>

##  <p align="center" style="color:#5D6D7E;">IMPORTACIONES</p>

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from imblearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
import sklearn.metrics as metrics
from regressors import stats
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import balanced_accuracy_score
from xgboost import XGBClassifier
from sklearn.decomposition import PCA

from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, BaggingClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, precision_score, recall_score, \
roc_curve, roc_auc_score, ConfusionMatrixDisplay, multilabel_confusion_matrix
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler


import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

## <p align="center" style="color:#5D6D7E;">MINI-AN√ÅLISIS EXPLORATORIO DE DATOS</p>

In [2]:
ob_train = pd.read_csv("./ob_train.csv")

In [39]:
ob_train.head(20)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,NObeyesdad
0,Male,24,1.70,82.0,yes,yes,2,2,Sometimes,no,2.8,no,0.0,1.0,Sometimes,Overweight_Level_II
1,Female,18,1.56,57.0,yes,yes,2,3,Frequently,no,2.0,no,1.0,1.0,no,Normal_Weight
2,Female,18,1.71,50.0,yes,yes,1,1,Sometimes,no,1.9,no,0.9,1.7,no,Insufficient_Weight
3,Female,20,1.71,131.0,yes,yes,3,3,Sometimes,no,1.7,no,1.5,0.8,Sometimes,Obesity_Type_III
4,Male,31,1.91,94.0,yes,yes,2,1,Sometimes,no,2.0,no,2.0,0.9,Sometimes,Overweight_Level_II
5,Male,18,1.75,52.0,yes,yes,2,3,Sometimes,no,2.1,no,1.9,1.0,Sometimes,Insufficient_Weight
6,Male,29,1.75,113.0,yes,yes,1,3,Sometimes,no,2.0,no,0.0,0.7,Sometimes,Obesity_Type_II
7,Male,29,1.75,118.0,yes,yes,1,3,Sometimes,no,2.0,no,0.6,0.0,Sometimes,Obesity_Type_II
8,Male,17,1.70,70.0,no,yes,2,3,Sometimes,no,3.0,yes,1.0,1.0,no,Overweight_Level_I
9,Female,26,1.64,111.0,yes,yes,3,3,Sometimes,no,2.6,no,0.0,0.2,Sometimes,Obesity_Type_III
10,Female,20,1.65,65.0,yes,yes,3,3,Sometimes,no,3.0,no,1.0,0.0,Sometimes,Overweight_Level_I
11,Male,22,1.70,70.0,yes,no,2,3,no,no,2.0,no,2.0,1.0,no,Normal_Weight
12,Male,18,1.81,108.0,yes,yes,2,2,Sometimes,no,2.5,no,1.0,0.6,no,Obesity_Type_I
13,Female,21,1.73,132.0,yes,yes,3,3,Sometimes,no,2.0,no,1.4,0.9,Sometimes,Obesity_Type_III
14,Female,20,1.57,49.0,no,no,2,1,Sometimes,no,1.0,no,3.0,2.0,no,Normal_Weight
15,Male,28,1.71,103.0,yes,yes,2,3,Sometimes,no,1.0,no,2.0,0.9,Sometimes,Obesity_Type_II
16,Female,34,1.70,80.0,yes,no,3,3,Always,no,2.0,no,0.0,0.0,no,Overweight_Level_II
17,Female,18,1.56,50.0,no,yes,3,3,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Normal_Weight
18,Male,22,1.70,80.0,yes,yes,1,3,Sometimes,no,2.0,no,0.0,1.0,no,Overweight_Level_II
19,Male,25,1.77,114.0,yes,yes,1,3,Sometimes,no,1.2,no,1.1,0.6,Sometimes,Obesity_Type_II

##### Informaci√≥n del dataset:

>- id: Identificaci√≥n √∫nica para cada persona en el conjunto de datos.

>- Gender: G√©nero de la persona

>- Age: Edad de la persona en a√±os.

>- Height: Altura de la persona en metros.

>- Weight: Peso de la persona en kilogramos.

>- family_history_with_overweight: Historial familiar de sobrepeso

>- FAVC: Consumidor de alimentos de alto contenido cal√≥rico 

>- FCVC: Frecuencia de consumo de verduras.

>- NCP: N√∫mero de comidas principales al d√≠a.

>- CAEC: Consumo de comida entre comidas 

>- SMOKE: Fumador 

>- CH2O: Consumo de agua diario en litros.

>- SCC: Consumo de calor√≠as vac√≠as 

>- FAF: Frecuencia de actividad f√≠sica.

>- TUE: Tiempo de uso de dispositivos electr√≥nicos

>- CALC: Consumo de alcohol 

>- MTRANS: Medio de transporte utilizado.

>- NObeyesdad: Nivel de obesidad

In [40]:
ob_train.tail()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,NObeyesdad
20753,Male,25,1.77,114.0,yes,yes,2,3,Sometimes,no,2.2,no,1.3,0.2,Sometimes,Obesity_Type_II
20754,Male,18,1.71,50.0,no,yes,3,4,Frequently,no,1.0,no,2.0,1.0,Sometimes,Insufficient_Weight
20755,Male,20,1.82,106.0,yes,yes,2,3,Sometimes,no,2.0,no,1.2,1.2,no,Obesity_Type_II
20756,Male,33,1.70,84.0,yes,yes,2,1,Sometimes,no,2.1,no,0.0,1.0,no,Overweight_Level_II
20757,Male,26,1.82,118.0,yes,yes,3,3,Sometimes,no,2.0,no,0.7,0.7,Sometimes,Obesity_Type_II

In [41]:
ob_train.shape

(20758, 16)

In [42]:
ob_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          20758 non-null  object
 1   Age                             20758 non-null  int64
 2   Height                          20758 non-null  float64
 3   Weight                          20758 non-null  float64
 4   family_history_with_overweight  20758 non-null  object
 5   FAVC                            20758 non-null  object
 6   FCVC                            20758 non-null  int64
 7   NCP                             20758 non-null  int64
 8   CAEC                            20758 non-null  object
 9   SMOKE                           20758 non-null  object
 10  CH2O                            20758 non-null  float64
 11  SCC                             20758 non-null  object
 12  FAF                             20758 non-null  float64
 13  TUE                             20758 non-null  float64
 14  CALC                            20758 non-null  object
 15  NObeyesdad                      20758 non-null  object
dtypes: float64(5), int64(3), object(8)
memory usage: 2.5+ MB

In [43]:
ob_train.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'NObeyesdad'],
      dtype='object')

In [44]:
ob_train.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,23.565950,1.700085,87.895703,2.301041,2.663407,2.028721,0.981785,0.616374
std,5.630841,0.087515,26.383853,0.588376,0.758286,0.609701,0.838865,0.601506
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,20.000000,1.630000,66.000000,2.000000,3.000000,1.800000,0.000000,0.000000
50%,22.000000,1.700000,84.000000,2.000000,3.000000,2.000000,1.000000,0.600000
75%,26.000000,1.760000,112.000000,3.000000,3.000000,2.500000,1.600000,1.000000
max,61.000000,1.980000,165.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [45]:
ob_train.describe(exclude=object).round(2)

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,20758.00,20758.00,20758.00,20758.00,20758.00,20758.00,20758.00,20758.00
mean,23.57,1.70,87.90,2.30,2.66,2.03,0.98,0.62
std,5.63,0.09,26.38,0.59,0.76,0.61,0.84,0.60
min,14.00,1.45,39.00,1.00,1.00,1.00,0.00,0.00
25%,20.00,1.63,66.00,2.00,3.00,1.80,0.00,0.00
50%,22.00,1.70,84.00,2.00,3.00,2.00,1.00,0.60
75%,26.00,1.76,112.00,3.00,3.00,2.50,1.60,1.00
max,61.00,1.98,165.00,3.00,4.00,3.00,3.00,2.00

In [46]:
ob_train.describe(include=object).round(2)

,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,NObeyesdad
count,20758,20758,20758,20758,20758,20758,20758,20758
unique,2,2,2,4,2,2,3,7
top,Female,yes,yes,Sometimes,no,no,Sometimes,Obesity_Type_III
freq,10422,17014,18982,17529,20513,20071,15066,4046

In [47]:
ob_train.isna().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
NObeyesdad                        0
dtype: int64

In [48]:
ob_train.isna().sum()/len(ob_train)*100

Gender                            0.0
Age                               0.0
Height                            0.0
Weight                            0.0
family_history_with_overweight    0.0
FAVC                              0.0
FCVC                              0.0
NCP                               0.0
CAEC                              0.0
SMOKE                             0.0
CH2O                              0.0
SCC                               0.0
FAF                               0.0
TUE                               0.0
CALC                              0.0
NObeyesdad                        0.0
dtype: float64

In [49]:
ob_train.duplicated().sum()

1448

#### Reporte de variables

In [50]:
def data_report(ob_train):
    cols = pd.DataFrame(ob_train.columns.values, columns=["COL_N"])
    types = pd.DataFrame(ob_train.dtypes.values, columns=["DATA_TYPE"])

    percent_missing = round(ob_train.isnull().sum() * 100 / len(ob_train), 2)
    percent_missing_df = pd.DataFrame(percent_missing.values, columns=["MISSINGS (%)"])

    unicos = pd.DataFrame(ob_train.nunique().values, columns=["UNIQUE_VALUES"])
    
    percent_cardin = round(unicos['UNIQUE_VALUES']*100/len(ob_train), 2)
    percent_cardin_df = pd.DataFrame(percent_cardin.values, columns=["CARDIN (%)"])

    concatenado = pd.concat([cols, types, percent_missing_df, unicos, percent_cardin_df], axis=1, sort=False)
    concatenado.set_index('COL_N', drop=True, inplace=True)


    return concatenado.T
        
data_report(ob_train)

COL_N,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,NObeyesdad
DATA_TYPE,object,int64,float64,float64,object,object,int64,int64,object,object,float64,object,float64,float64,object,object
MISSINGS (%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
UNIQUE_VALUES,2,43,51,116,2,2,3,4,4,2,21,2,31,21,3,7
CARDIN (%),0.01,0.21,0.25,0.56,0.01,0.01,0.01,0.02,0.02,0.01,0.1,0.01,0.15,0.1,0.01,0.03

## <p align="center" style="color:#5D6D7E;">MODELO MACHINE LEARNING - CLASIFICACI√ìN</p>

##### DIVISI√ìN DE DATOS

In [51]:
ob_train

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,NObeyesdad
0,Male,24,1.70,82.0,yes,yes,2,2,Sometimes,no,2.8,no,0.0,1.0,Sometimes,Overweight_Level_II
1,Female,18,1.56,57.0,yes,yes,2,3,Frequently,no,2.0,no,1.0,1.0,no,Normal_Weight
2,Female,18,1.71,50.0,yes,yes,1,1,Sometimes,no,1.9,no,0.9,1.7,no,Insufficient_Weight
3,Female,20,1.71,131.0,yes,yes,3,3,Sometimes,no,1.7,no,1.5,0.8,Sometimes,Obesity_Type_III
4,Male,31,1.91,94.0,yes,yes,2,1,Sometimes,no,2.0,no,2.0,0.9,Sometimes,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,Male,25,1.77,114.0,yes,yes,2,3,Sometimes,no,2.2,no,1.3,0.2,Sometimes,Obesity_Type_II
20754,Male,18,1.71,50.0,no,yes,3,4,Frequently,no,1.0,no,2.0,1.0,Sometimes,Insufficient_Weight
20755,Male,20,1.82,106.0,yes,yes,2,3,Sometimes,no,2.0,no,1.2,1.2,no,Obesity_Type_II
20756,Male,33,1.70,84.0,yes,yes,2,1,Sometimes,no,2.1,no,0.0,1.0,no,Overweight_Level_II
20757,Male,26,1.82,118.0,yes,yes,3,3,Sometimes,no,2.0,no,0.7,0.7,Sometimes,Obesity_Type_II

In [52]:
encoder= LabelEncoder()

for columna in ob_train.columns:
    if ob_train[columna].dtype== "object":
        ob_train[columna + "_encoded"] =encoder.fit_transform(ob_train[columna])

ob_train

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,...,CALC,NObeyesdad,Gender_encoded,family_history_with_overweight_encoded,FAVC_encoded,CAEC_encoded,SMOKE_encoded,SCC_encoded,CALC_encoded,NObeyesdad_encoded
0,Male,24,1.70,82.0,yes,yes,2,2,Sometimes,no,...,Sometimes,Overweight_Level_II,1,1,1,2,0,0,1,6
1,Female,18,1.56,57.0,yes,yes,2,3,Frequently,no,...,no,Normal_Weight,0,1,1,1,0,0,2,1
2,Female,18,1.71,50.0,yes,yes,1,1,Sometimes,no,...,no,Insufficient_Weight,0,1,1,2,0,0,2,0
3,Female,20,1.71,131.0,yes,yes,3,3,Sometimes,no,...,Sometimes,Obesity_Type_III,0,1,1,2,0,0,1,4
4,Male,31,1.91,94.0,yes,yes,2,1,Sometimes,no,...,Sometimes,Overweight_Level_II,1,1,1,2,0,0,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,Male,25,1.77,114.0,yes,yes,2,3,Sometimes,no,...,Sometimes,Obesity_Type_II,1,1,1,2,0,0,1,3
20754,Male,18,1.71,50.0,no,yes,3,4,Frequently,no,...,Sometimes,Insufficient_Weight,1,0,1,1,0,0,1,0
20755,Male,20,1.82,106.0,yes,yes,2,3,Sometimes,no,...,no,Obesity_Type_II,1,1,1,2,0,0,2,3
20756,Male,33,1.70,84.0,yes,yes,2,1,Sometimes,no,...,no,Overweight_Level_II,1,1,1,2,0,0,2,6
20757,Male,26,1.82,118.0,yes,yes,3,3,Sometimes,no,...,Sometimes,Obesity_Type_II,1,1,1,2,0,0,1,3

### REGRESION LOGISTICA

#### train y test

In [53]:
x= ob_train.drop("NObeyesdad_encoded",axis=1)
y= ob_train["NObeyesdad_encoded"].values
x_train, x_test,y_train, y_test =train_test_split(x,y,test_size=0.2, random_state=42)

In [54]:
encoder= LabelEncoder()

for columna in x_train.columns:
    if x_train[columna].dtype== "object":
        x_train[columna] =encoder.fit_transform(x_train[columna])
        x_test[columna]= encoder.transform(x_test[columna])

#### Escalados

In [55]:
esc= StandardScaler()
min_esc=MinMaxScaler()

train_esc=esc.fit_transform(x_train)
train_min_esc = min_esc.fit_transform(x_train)

test_esc= esc.transform(x_test)
test_min_esc=min_esc.transform(x_test)

In [56]:
lasso= LogisticRegression(penalty="l1",solver="liblinear",C=1.0)
lasso.fit(x_train, y_train)

LogisticRegression(penalty='l1', solver='liblinear')

#### PCA

In [57]:
pipeline= Pipeline([
    ("pca",PCA(n_components=2)),
    ("clf",SVC())
])

#### Modelo

In [58]:
scores= cross_val_score(pipeline,x_train,y_train, cv=5)
print("Cross Validation Scores:",scores)
print("Mean Accuracy:", scores.mean())

Cross Validation Scores: [0.69536424 0.69978922 0.70310148 0.69978922 0.71695273]
Mean Accuracy: 0.7029993758362896

In [59]:
pipeline.fit(x_train, y_train)
y_pred= pipeline.predict(x_test)
test_balanced_accuracy= balanced_accuracy_score(y_test,y_pred)
print("Test Balanced Accuracy:",test_balanced_accuracy)

Test Balanced Accuracy: 0.6799663894612304

In [60]:
models= {
    "Linear Regression":LinearRegression(),
    "Random Forest Regressor":RandomForestRegressor(),
    "SVR":SVR(),
    "Logistic Regression":LogisticRegression(),
    "KNN":KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "XGBoost":XGBClassifier(),
    "LGBMClassifier":LGBMClassifier(),
    "GradientBoostingClassifier": GradientBoostingClassifier(), 
    "AdaboostClassifier":AdaBoostClassifier(),
    "Catboost": CatBoostClassifier(verbose=False)}

result=[]

for name, model in models.items():
    pipeline.set_params(clf=model)
    pipeline.fit(x_train,y_train)
    train_score= pipeline.score(x_train, y_train)
    test_score= pipeline.score(x_test,y_test)
    result.append({"Modelo":name,"Entrenamiento":train_score,"Puntuaci√≥n":test_score})

ob_train= pd.DataFrame(result)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000198 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 16606, number of used features: 2
[LightGBM] [Info] Start training from score -2.117117
[LightGBM] [Info] Start training from score -1.911230
[LightGBM] [Info] Start training from score -1.948141
[LightGBM] [Info] Start training from score -1.857720
[LightGBM] [Info] Start training from score -1.633574
[LightGBM] [Info] Start training from score -2.145531
[LightGBM] [Info] Start training from score -2.112625

In [61]:
ob_train.sort_values("Puntuaci√≥n",ascending=False)

                        Modelo  Entrenamiento  Puntuaci√≥n
1      Random Forest Regressor       0.991296    0.935892
5                Decision Tree       1.000000    0.923170
4                          KNN       0.925027    0.897881
6                      XGBoost       0.933638    0.896435
7               LGBMClassifier       0.928038    0.893545
10                    Catboost       0.891304    0.866329
8   GradientBoostingClassifier       0.865832    0.841281
3          Logistic Regression       0.593822    0.603324
2                          SVR       0.478460    0.494153
9           AdaboostClassifier       0.452607    0.461946
0            Linear Regression       0.221342    0.230162

In [62]:
param_grid={
    "KNN":{
        "model":models["KNN"],
        "param_grid":{
        "n_neighbors": [3,5,10],
        "weights":["uniform","distance"],
        "metric":["euclidean","manhattan"]}},
    "Decision Tree":{
        "model":models["Decision Tree"],
        "param_grid":{
        "max_depth":[None, 5,10],
        "min_samples_split": [2, 5,10],
        "min_samples_leaf": [1,2,4]}},
    "Random Forest": {
        "model":models["Random Forest Regressor"],
        "param_grid": {
        "n_estimators": [50,100,200],
        "max_depth": [None, 10, 20],
        "min_samples_split": [2, 5,10],
        "min_samples_leaf": [1,2, 4]}}
}


for model_name, params in param_grid.items():
    model=params["model"]
    param_grid=params["param_grid"]
    
    grid_search= GridSearchCV(model,param_grid, cv=5,scoring="accuracy", n_jobs=-1)
    grid_search.fit(x_train, y_train)
    
    print(f"Mejores hiperpar√°metros para {model_name}:{grid_search.best_params_}")

Mejores hiperpar√°metros para KNN:{'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'}
Mejores hiperpar√°metros para Decision Tree:{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Mejores hiperpar√°metros para Random Forest:{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}

In [63]:
knn= KNeighborsClassifier()
knn.fit(x_train,y_train)

decision_tree= DecisionTreeClassifier()
decision_tree.fit(x_train,y_train)

random_forest= RandomForestClassifier()
random_forest.fit(x_train,y_train)

knn_score =knn.score(x_test,y_test)
dt_score= decision_tree.score(x_test, y_test)
randomf_score= random_forest.score(x_test, y_test)

print("KNN Accuracy:",knn_score)
print("Decision Tree Accuracy:",dt_score)
print("Random Forest Accuracy:",randomf_score)

KNN Accuracy: 0.9499036608863198
Decision Tree Accuracy: 1.0
Random Forest Accuracy: 0.9971098265895953

In [72]:
final_decisiontree= DecisionTreeClassifier(max_depth=None, min_samples_leaf=1,min_samples_split=2)

final_decisiontree.fit(x_train,y_train)

dtree_score= final_decisiontree.score(x_test,y_test)
print("Final Decision Tree Accuracy:",dtree_score)

Final Decision Tree Accuracy: 1.0

In [73]:
y_pred= final_decisiontree.predict(x_test)

accuracy= accuracy_score(y_test, y_pred)
precision= precision_score(y_test, y_pred, average="weighted")
recall=recall_score(y_test, y_pred, average="weighted")
f1= f1_score(y_test, y_pred, average="weighted")

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0

#### GUARDAR EL MODELO

In [77]:
import pickle

with open('modelo.pkl', 'wb') as archivo_modelo:
    pickle.dump(ob_train, archivo_modelo)